research_task:
  description: >
    Access and read the file stored in the S3 bucket {my_bucket}. Analyze its contents, extract key information, and provide a concise summary highlighting the main settings, values, and any notable configurations. 
    At the end, generate and return a summary file containing the extracted insights.
  expected_output: >
    A well-structured summary of the file's contents, formatted clearly within triple backticks (```), along with a downloadable summary file (e.g., summary.txt or summary.md).
  agent: researcher